### ISSUE TITLE
Clone the repository to retain it safely in the future

### ISSUE THREAD

**Issue by pattacini** [Iaxama/test-operational-control-with-icub-Iaxama#3]
Hi @Iaxama 

To retain this repository in the future no matter what, you should clone it (don't fork) and store it safely on GitHub account.

I've recently realized that deleting the assignment from the GitHub Education dashboard will cause that all the participant repositories will be deleted too 😲, even if their ownership has been transferred.

**Comment by pattacini** [comment]
Hi @Iaxama ,

Differently from what I said in this [post](https://github.com/robotology/robotology.github.io/issues/15#issuecomment-270758722), you should [**duplicate** this repository](https://help.github.com/articles/duplicating-a-repository/#mirroring-a-repository).

**Comment by Iaxama** [comment]
I've followed the instructions for mirroring the repo. I hope it's alright now.

**Comment by pattacini** [comment]
Actually, I don't see your new repository on GitHub.
Perhaps, you didn't push it yet.

Just asking because I'm going to delete this instead.

**Comment by Iaxama** [comment]
Now it should be done... for real :smile:

**Comment by pattacini** [comment]
Well done.
